// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core_graph_v2.Data;

namespace core_graph_v2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("core_graph_v2.Models.Action", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActionGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ActionNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("core_graph_v2.Models.ActionCmt", b =>
                {
                    b.Property<int>("ActionCmtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<string>("CView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionCmtId");

                    b.HasIndex("ActionId");

                    b.ToTable("ActionCmt");
                });

            modelBuilder.Entity("core_graph_v2.Models.ClashCheck", b =>
                {
                    b.Property<string>("CheckItem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BadPartCnt")
                        .HasColumnType("int");

                    b.Property<int>("ClashesCnt")
                        .HasColumnType("int");

                    b.Property<int>("DelayedPartCnt")
                        .HasColumnType("int");

                    b.Property<int>("EditCnt")
                        .HasColumnType("int");

                    b.Property<string>("LastUpdateDt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoneCnt")
                        .HasColumnType("int");

                    b.Property<int>("OptionalCnt")
                        .HasColumnType("int");

                    b.Property<int>("SevereCnt")
                        .HasColumnType("int");

                    b.Property<int>("UndefinedCnt")
                        .HasColumnType("int");

                    b.HasKey("CheckItem");

                    b.ToTable("ClashCheck");
                });

            modelBuilder.Entity("core_graph_v2.Models.User", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idx");

                    b.ToTable("User");
                });

            modelBuilder.Entity("core_graph_v2.Models.ActionCmt", b =>
                {
                    b.HasOne("core_graph_v2.Models.Action", null)
                        .WithMany("ActionCmt")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core_graph_v2.Models.Action", b =>
                {
                    b.Navigation("ActionCmt");
                });
#pragma warning restore 612, 618
        }
    }
}
